cmake_minimum_required(VERSION 3.8)
project(
	CMakexternal
	VERSION 1.0
)


include(ExternalProject)

set_property(DIRECTORY PROPERTY EP_BASH ${CMAKE_BINARY_DIR}/subProject)

message(STATUS "EXTERNAL_NAME: ${EXTERNAL_NAME}\nEXTERNAL_ARG: ${EXTERNAL_ARG}")
file(APPEND ${CMAKE_SOURCE_DIR}/current_log.txt "EXTERNAL_NAME: ${EXTERNAL_NAME}\nEXTERNAL_ARG: ${EXTERNAL_ARG}")
ExternalProject_Add(
	${EXTERNAL_NAME}
	${EXTERNAL_ARG}
	CMAKE_ARGS
		-DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
		-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
		-DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
		-DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
	BUILD_ALWAYS 1
	LOG_CONFIGURE 1
	LOG_BUILD 1
	LOG_INSTALL 1

)
if(install_prefix)
	install(DIRECTORY
		${install_prefix}
		DESTINATION ${CMAKE_INSTALL_PREFIX}
	)
endif()



