#!/usr/bin/bash

function e()
{
	if [ $? != 0 ]
	then
		exit 1
	fi
}
mkdir -p build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/prefix -DCMAKE_BUILD_TYPE=Debug -G"Ninja"
# -DCMAKE_CXX_COMPILER_LAUNCHER=ccache 
e
cmake --build . --parallel
e

# cmake --build . --target install
./bin/main
e

