#!/usr/bin/bash

function e()
{
	if [ $? != 0 ]
	then
		exit 1
	fi
}

mkdir -p build
cd build
cmake -DCMAKE_INSTALL_PREFIX=$PWD/prefix -G"Ninja" ..
e
cmake --build .
e

# cmake --build . --target install
./bin/sort-test.exe



